# Generated by Django 5.1.6 on 2025-02-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_group_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group-post',
            new_name='group',
        ),
    ]
