# Generated by Django 5.1.6 on 2025-02-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='reaction_type',
            new_name='type',
        ),
    ]
