# Generated by Django 5.1.6 on 2025-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='postmedia',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='post_media/'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='thumbnail_file',
            field=models.FileField(blank=True, upload_to='post_media/thumbnails/'),
        ),
    ]
