# Generated by Django 5.1.6 on 2025-03-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_postmedia_media_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
