# Generated by Django 5.1.6 on 2025-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postmedia_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='post_media/'),
        ),
    ]
