# Generated by Django 5.1.6 on 2025-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_commentreaction_sharedpostcommentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
