# Generated by Django 5.1.6 on 2025-03-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_click_count_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpost',
            name='parent_share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_shares', to='posts.sharedpost'),
        ),
    ]
