# Generated by Django 5.1.6 on 2025-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to='stories/thumbnails/'),
        ),
    ]
