# Generated by Django 5.1.6 on 2025-03-28 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_2fa_enabled_user_otp_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_picture_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to='cover_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
