# Generated by Django 5.1.6 on 2025-03-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_cover_picture_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_picture_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True),
        ),
    ]
