# Generated by Django 5.1.6 on 2025-02-25 21:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('friend_request', 'Friend Request'), ('like', 'Like'), ('comment', 'Comment'), ('reaction', 'Reaction'), ('tag', 'Tag'), ('group_invite', 'Group Invite'), ('group_update', 'Group Update'), ('follower_activity', 'Follower Activity')], max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(verbose_name=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
